### PR TITLE
Fixed Navbar UI

### LINKED ISSUE #97: Navbar UI Fix
image

image

- navbar should be sticky, meaning that it will move when the user scrolls down the website.
- add a little margining to the right 
- try to fix the select bar, it should match with the figma file (should be thicker)

### PR DESCRIPTION
**Pull request by raulrazo**
Screenshot 2024-02-09 at 3 02 13 PM
Screenshot 2024-02-09 at 3 02 45 PM

### CODE REVIEW

**Review by seanquiambao — CHANGES_REQUESTED** [review]
image

everything else looks fine, but make sure the navigation bar is mobile responsive. reduce the amount of space between the items

**Comment by raulrazo** [comment]
Here are my updates to the mobile navbar:
Screenshot 2024-02-05 at 3 49 43 PM
Screenshot 2024-02-05 at 3 50 06 PM
Screenshot 2024-02-05 at 3 50 16 PM

File: src/components/Navigation.jsx [hunk 1]
```diff
@@ -43,17 +42,21 @@ const Navigation = () => {
...
+                  }
+                ></div>
               </div>
             </Nav.Link>
           ))}
 
           <Nav.Link
             href="\"
-            className="flex justify-center items-center text-white text-3xl font-bold w-44 h-11 rounded-full bg-gradient-to-r from-isa-yellow-200 to-isa-yellow-100"
+            className="flex justify-center items-center text-white text-3xl font-bold w-44 h-11 rounded-full bg-gradient-to-r from-isa-yellow-200 to-isa-yellow-100 md:mt-0 mt-2"
```
Comment (seanquiambao) [inline src/components/Navigation.jsx]: image

the join button looks a little misaligned here. what does the mobile responsiveness for the join button supposed to do here?

**Review by seanquiambao — CHANGES_REQUESTED** [review]

**Review by seanquiambao — APPROVED** [review]
