### PR TITLE
Calendar Fix

### LINKED ISSUE #156: Calendar Fix
- Test out Google Calendar Integration and fix any problems related to the calendar.

`
const startDate = new Date(
      new Date().getTime() - 60 * 60 * 24 * 7 * 10 * 1000
    ).toISOString();
`
set the startDate to a larger value until you see events back in march 2022

image

- Also lighten today's date. It should not be transparent. You can add another tailwind color like `yellow-300` if needed, but do not use opacity.

### PR DESCRIPTION
**Pull request by achen409**
image

### CODE REVIEW

File: src/app/about/page.js
Comment (seanquiambao) [inline src/app/about/page.js:1]: remove the changes from this branch

File: src/components/home/About.jsx
Comment (seanquiambao) [inline src/components/home/About.jsx:1]: remove the changes from this branch

File: src/components/events/Calendar.jsx [hunk 1]
```diff
@@ -19,7 +19,7 @@ const CalendarEvents = () => {
 
   useEffect(() => {
     const startDate = new Date(
-      new Date().getTime() - 60 * 60 * 24 * 7 * 10 * 1000
+      new Date().getTime() - 60 * 60 * 24 * 7 * 10 * 100000
     ).toISOString();
```
Comment (seanquiambao) [inline src/components/events/Calendar.jsx:23]: image

events should show the title. (hint console log the events and look for the titles from the console log)

**Review by seanquiambao — CHANGES_REQUESTED** [review]

File: src/app/about/page.js [hunk 2]
```diff
@@ -49,7 +49,7 @@ const About = () => {
           initial="start"
           whileInView="end"
           transition={{ ease: "easeOut", duration: 2, delay: 0.4 }}
-          className="hidden lg:block absolute 2xl:-right-[13%] -right-[25%] scale-140"
+          className="hidden xl:block absolute -right-[20%] scale-140"
```
Comment (seanquiambao) [inline src/app/about/page.js]:
```suggestion
          className="hidden lg:block absolute 2xl:-right-[13%] -right-[25%] scale-140"
```

File: src/app/about/page.js [hunk 3]
```diff
@@ -61,7 +61,11 @@ const About = () => {
           transition={{ ease: "easeOut", duration: 2, delay: 0.2 }}
           className="hidden lg:block absolute top-[500px] 2xl:-left-[13%] -left-[25%] scale-140"
         >
-          <Image src={Sun} alt="Blue sun" />
+          <Image
+            src={Sun}
+            alt="Blue sun"
+            className="hidden xl:block absolute top-[500px] -left-[25%] scale-140"
+          />
```
Comment (seanquiambao) [inline src/app/about/page.js]:
```suggestion
         <Image src={Sun} alt="Blue sun" />
```

File: src/components/home/About.jsx [hunk 4]
```diff
@@ -8,8 +8,8 @@ import logo from "@/public/assets/logo.svg";
 const About = () => {
   return (
     <div className="flex flex-col items-center">
-      <div className="flex flex-col xl:flex-row items-center justify-center px-10 lg:w-5/6">
-        <div className="flex justify-center items-center w-full md:w-2/5 xl:mr-10">
+      <div className="flex flex-col md:flex-row items-center justify-center px-10 lg:w-5/6">
+        <div className="flex justify-center items-center w-full md:w-2/5">
```
Comment (seanquiambao) [inline src/components/home/About.jsx]:
```suggestion
      <div className="flex flex-col xl:flex-row items-center justify-center px-10 lg:w-5/6">
        <div className="flex justify-center items-center w-full md:w-2/5 xl:mr-10">
```

**Review by seanquiambao — APPROVED** [review]
