### PR TITLE
fix involve section issue

### LINKED ISSUE #70: Involved Fix
image

- when the user hovers over text or icons, both of them need to transition at the same time. (https://tailwindcss.com/docs/hover-focus-and-other-states)
- if you hover under the social components, they should not transition to blue. this is because the components have bottom padding. there should be margining applied to the whole involved component, rather than the social components themselves.

### PR DESCRIPTION
**Pull request by mailynnguyen**
image

### CODE REVIEW

File: src/components/home/Social.jsx [hunk 1]
```diff
@@ -3,13 +3,13 @@ import Link from "next/link";
 const Social = ({ icon, text, link }) => {
   return (
     <Link
-      className="hover:!text-isa-blue-100 flex flex-col cursor-pointer h-25 items-center text-isa-yellow-100 m-4 px-8 pt-8 pb-36"
+      className="hover:!text-isa-blue-100 hover:!bg-gradient-to-r hover:!from-isa-blue-200 hover:!bg-clip-text hover:!to-isa-blue-100 flex flex-col cursor-pointer h-25 items-center text-isa-yellow-100 m-4 px-8 pt-8"
```
Comment (seanquiambao) [inline src/components/home/Social.jsx]: change `px` and `pt` to margin instead. adjust spacing as needed

**Review by seanquiambao — CHANGES_REQUESTED** [review]

**Review by seanquiambao — APPROVED** [review]
